name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating and updating releases
      actions: write # Required for creating GitHub releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Download Go modules
      run: go mod download

    - name: Run unit tests
      run: go test -v ./...

    - name: Generate coverage report
      run: |
        PKGS=$(go list ./... | grep -v '/cmd/')
        go test -coverpkg=./... -covermode=atomic -coverprofile=coverage.out $PKGS

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.out

    #- name: Run golangci-lint
    #  uses: golangci/golangci-lint-action@v6
    #  with:
    #    version: v1.58
    #    args: --timeout=5m

    - name: Build binaries
      if: github.event_name != 'pull_request'
      run: |
        PROJECT_NAME="ast2llm-go"
        BUILD_DIR="./build"
        mkdir -p $BUILD_DIR

        PLATFORMS="linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64"

        for platform in $PLATFORMS;
        do
          GOOS=$(echo $platform | cut -d'/' -f1)
          GOARCH=$(echo $platform | cut -d'/' -f2)
          OUTPUT_NAME="$PROJECT_NAME-$GOOS-$GOARCH"
          if [ "$GOOS" == "windows" ]; then
            OUTPUT_NAME+=".exe"
          fi

          echo "Building $OUTPUT_NAME for $GOOS/$GOARCH"
          env GOOS=$GOOS GOARCH=$GOARCH go build -o $BUILD_DIR/$OUTPUT_NAME ./cmd/server
        done

    - name: Install UPX
      if: github.event_name != 'pull_request'
      run: |
        sudo apt-get update
        sudo apt-get install -y upx-ucl

    - name: Compress binaries with UPX
      if: github.event_name != 'pull_request'
      run: |
        BUILD_DIR="./build"
        find $BUILD_DIR -type f -exec upx {} \;

    - name: Generate SHA256 checksums
      if: github.event_name != 'pull_request'
      run: |
        BUILD_DIR="./build"
        cd $BUILD_DIR
        # Check if sha256sum is available (Linux) or shasum (macOS)
        if command -v sha256sum >/dev/null; then
          for file in *; do
            [ -f "$file" ] || continue # Skip directories
            sha256sum "$file" > "$file.sha256"
            echo "Generated checksum for $file"
          done
        elif command -v shasum >/dev/null; then
          for file in *; do
            [ -f "$file" ] || continue # Skip directories
            shasum -a 256 "$file" > "$file.sha256"
            echo "Generated checksum for $file"
          done
        else
          echo "Warning: Neither sha256sum nor shasum found. Cannot generate checksums."
        fi

    - name: Upload artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: ./build/

    - name: Get latest release tag
      id: get_latest_release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "Retrieving latest release tag..."
        LATEST_TAG=$(gh release view --json tagName -q .tagName || echo "")
        echo "Latest tag: $LATEST_TAG"
        echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate changelog
      id: generate_changelog
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        LAST_RELEASE_TAG="${{ steps.get_latest_release.outputs.latest_tag }}"
        CHANGELOG_CONTENT=""

        if [ -z "$LAST_RELEASE_TAG" ]; then
          echo "No previous release tag found. Generating changelog from current HEAD."
          CHANGELOG_CONTENT=$(git log HEAD --pretty=format:'* %h %s (%an)')
        else
          echo "Previous release tag found: $LAST_RELEASE_TAG. Generating changelog since last release."
          CHANGELOG_CONTENT=$(git log "$LAST_RELEASE_TAG"..HEAD --pretty=format:'* %h %s (%an)')
        fi

        # Escape newlines for multi-line output
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Generate release tag and name
      id: generate_release_info
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        COMMIT_DATE=$(date -d "${{ github.event.head_commit.timestamp }}" +%Y%m%d)
        FULL_SHA="${{ github.sha }}"
        LAST_FOUR_SHA="${FULL_SHA: -4}"
        echo "formatted_date=$COMMIT_DATE" >> "$GITHUB_OUTPUT"
        echo "short_sha=$LAST_FOUR_SHA" >> "$GITHUB_OUTPUT"

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.generate_release_info.outputs.formatted_date }}-${{ steps.generate_release_info.outputs.short_sha }}
        name: Release v${{ steps.generate_release_info.outputs.formatted_date }}-${{ steps.generate_release_info.outputs.short_sha }}
        draft: false
        prerelease: false
        files: | 
          ./build/*
        generate_release_notes: true
        # The user requested to generate release notes with commits since the previous release. 
        # This requires the gh cli, and the github_token for access
        body: |
          Changes since last release (${{ steps.get_latest_release.outputs.latest_tag }}):
          ```
          ${{ steps.generate_changelog.outputs.changelog }}
          ```
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 